feat: Make create and read function
roadtocoldroad/to-do-list pull request #4
Opened 2022-11-16 14:30 UTC by parkcoldroad

### 기능 구현

1. todo를 생성하는 기능을 만들었습니다.
2. todo를 조회하는 기능을 만들었습니다.
3. todo를 id로 조회하는 기능을 만들었습니다.
4. JSON을 사용하여 API를 구현하였습니다.

### 실행 방법

1. 코드를 다운로드 (또는 clone) 한다
2. `source venv/bin/activate `을 입력해 가상 환경을 실행시킨다
3. `pip install -r requirements.txt` 을 입력해 연관된 패키지를 다운받는다
4. `flask --app todo init-db` 을 입력해 db를 초기화한다.
5. `flask --app todo run`을 입력해 실행한다

2022-11-21 10:23 UTC, junghoon-vans requested changes

2022-11-21 10:23 UTC, junghoon-vans commented on requirements.txt
> +Flask-SQLAlchemy==3.0.2
필요없는 의존성은 지우도록 합시다.

2022-11-21 10:23 UTC, junghoon-vans commented on app/models.py
> +import sqlite3
데이터베이스 생성하는 raw query가 담긴 내용은 `models.py`에 넣기에는 적절하지 않아 보입니다.

2022-11-21 10:23 UTC, junghoon-vans commented on app/app.py
> +def index():
메서드 별로 나누어서 라우팅하는 게 더 나은 방법인 것 같습니다.

2022-11-21 10:23 UTC, junghoon-vans commented on app/app.py
> +        con = sql.connect('database.db')
DB 커넥션하는 모듈을 만들어서 관리하도록 리팩터링해주세요.

2022-11-21 10:23 UTC, junghoon-vans commented on app/app.py
> +def read_data(SQL,id):
라우팅 로직과 DB 조작 로직을 분리해주세요.

2022-11-21 10:23 UTC, junghoon-vans commented on app/app.py
> + app.secret_key = 'super secret key'
credential 정보를 환경변수를 사용해서 숨기는 방법을 고려해보세요.

2022-11-21 10:37 UTC, jongwooo requested changes
과제하시느라 고생 많으셨습니다. Comment 위주로 살펴봐주세요. 그리고 [e693e1f](https://github.com/roadtocoldroad/to-do-list/pull/4/commits/e693e1f689ec9136be7901323633d045352ba797)의 경우 `flask Project`보다 전부 소문자로 작성하는 것을 추천드립니다. 일관성 있는 커밋 메시지를 작성할 수 있도록 관련 레퍼런스를 찾아보시는 것도 좋을 것 같습니다. 고생하셨습니다.

2022-11-21 10:37 UTC, jongwooo commented on .gitignore
>  # User-specific stuff
```suggestion
.idea/
```

`.idea/`로 축약해서 작성하면 더 좋을 것 같습니다.

2022-11-21 10:37 UTC, jongwooo commented on app/app.py
> +        con.commit()
어떤 역할을 하는지 알기 쉬운 변수명, 함수명으로 바꾸어보세요.

2022-11-21 10:37 UTC, jongwooo commented on app/models.py
> +    '''
9-15줄 인덴트를 수정해주세요.

2022-11-21 10:37 UTC, jongwooo commented on app/static/main.css
> +.mark{font-size: 10px;}
일관성 있는 인덴트 규칙을 가지고 작성해주세요.

2022-11-21 10:37 UTC, jongwooo commented on app/templates/index.html
> +</html>
html로 출력하는 것도 좋은 방법이지만 프로젝트 본래의 취지대로 REST API 형태로 개발해보세요.

2022-11-21 10:41 UTC, junghoon-vans commented on app/models.py
> +    '''
가능하다면 프로젝트 시작 시 필요한 테이블은 별도의 `.sql` 파일로 정의해주시는게 좋습니다.

2022-11-23 16:57 UTC, jongwooo reviewed
PEP8에서는 홑따옴표(')와 쌍따옴표(")의 사용에 대한 어떠한 권장사항도 없습니다. 다만 가독성을 위해 규칙을 정해서 사용하는 것이 좋습니다. 이 점 참고하여 코드를 개선해보세요:)

[https://peps.python.org/pep-0008/#string-quotes](https://peps.python.org/pep-0008/#string-quotes)

2022-11-26 01:29 UTC, jongwooo requested changes

2022-11-26 01:29 UTC, jongwooo commented on todo/schema.sql
> +    "url" text)
테이블명, 컬럼명을 쌍따옴표(")로 묶어서 표기해주셨는데 혹시 이유가 있을까요?

2022-11-26 01:29 UTC, jongwooo commented on todo/routes.py
> +bp = Blueprint('main', __name__, url_prefix='/')
`url_prefix`를 route에서 선언하면 prefix를 확인할 때 각 route의 코드를 확인해야 하는 번거로움이 있습니다. 아래의 링크를 참고하여 개선해보세요:)

[https://flask-docs-kr.readthedocs.io/ko/latest/blueprints.html](https://flask-docs-kr.readthedocs.io/ko/latest/blueprints.html)

2022-11-26 01:29 UTC, jongwooo commented on todo/routes.py
> +        "select * from todo where todo_id = ?", (todo_id,)
아래와 같이 sql 문법은 가독성을 위해 대문자로 작성해보세요.
```suggestion
        "SELECT * FROM todo WHERE todo_id = ?", (todo_id,)
```

2022-11-26 09:18 UTC, parkcoldroad commented on todo/schema.sql
> +    "url" text)
> 테이블명, 컬럼명을 쌍따옴표(")로 묶어서 표기해주셨는데 혹시 이유가 있을까요?

따로 이유가 있지는 않아서 쌍따옴표 없이 표기하는걸로 수정했습니다

2022-11-26 11:42 UTC, jongwooo requested changes

2022-11-26 11:42 UTC, jongwooo commented on todo/routes.py
> +@bp.route('/<string:todo_id>')
method 지정이 되어 있지 않습니다. 요구사항을 준수하도록 변경해보세요.

2022-11-26 13:37 UTC, junghoon-vans requested changes

2022-11-26 13:37 UTC, junghoon-vans commented on todo/routes.py
> +    cursor.execute("INSERT INTO todo(TITLE,URL) VALUES (?,?)", (params['title'], request.url))
url을 데이터베이스에 저장할 필요는 없어 보입니다.

2022-11-27 11:10 UTC, junghoon-vans approved these changes
과제하시느라 수고많으셨습니다.

2022-11-27 11:13 UTC, jongwooo approved these changes

2022-11-27 14:39 UTC, merged